const GET_TASKS = "GET_TASKS";
const GET_TASK_COUNT = "GET_TASK_COUNT";
const SET_SORT_FIELD_VALUE = "SET_SORT_FIELD_VALUE";
const SET_SORT_DIRECTION_VALUE = "SET_SORT_DIRECTION_VALUE";
const SET_PAGE_VALUE = "SET_PAGE_VALUE";
const SET_PAGES = "SET_PAGES";
const SET_IS_CREATE_TASK_POPUP_OPEN = "SET_IS_CREATE_TASK_POPUP_OPEN";
const SET_IS_EDIT_TASK_POPUP_OPEN = "SET_IS_EDIT_TASK_POPUP_OPEN";
const SET_IS_LOGIN_POPUP_OPEN = "SET_IS_LOGIN_POPUP_OPEN";
const SET_SELECTED_TASK = "SET_SELECTED_TASK";
const SET_IS_LOGGED_IN = "SET_IS_LOGGED_IN";

export {
  GET_TASK_COUNT,
  GET_TASKS,
  SET_SORT_FIELD_VALUE,
  SET_SORT_DIRECTION_VALUE,
  SET_PAGE_VALUE,
  SET_PAGES,
  SET_IS_CREATE_TASK_POPUP_OPEN,
  SET_IS_EDIT_TASK_POPUP_OPEN,
  SET_IS_LOGIN_POPUP_OPEN,
  SET_SELECTED_TASK,
  SET_IS_LOGGED_IN
};
